dbt_test_project:
  outputs:
    dev:
      dbname: card_stats
      host: localhost
      pass: '1947'
      port: 5432
      schema: test
      threads: 1
      type: postgres
      user: hurin19
  target: dev
kdbt:
  outputs:
    dev:
      dbname: card_stats
      host: 192.168.1.133
      pass: '1947'
      port: 5432
      schema: test
      threads: 1
      type: postgres
      user: hurin19
  target: dev
